---
- name: Pull Docker Image
  hosts: all
  tasks:
    - name: Pull calculator.Calculator Image from Docker Hub
      docker_image:
        name: shubhimaheshwari/calculator-repo
        source: pull